public enum DurationType
{
	NONE = 0,
	AUTO = 1,
	TRIGGER = 2,
	INFINITE = 3,
	CHANNELING = 4,
	AUTO_END = 5,
	AUTO_UPDATE = 6
}

public enum StackType
{
	NONE = 0,
	STACK = 1,
	DUPLICATION = 2,
	USE = 3,
	BURST = 4,
	CHARGE = 5,
	EXAUST_CHARGE = 6,
	AUTO_DECREASE = 7,
	AUTO_INCREASE = 8,
	STACK_AVAILABLE = 9,
	AUTO_INCREASE_STACK_AVAILABLE = 10,
	APPEARANCE_STACK = 11,
	EXAUST_CHARGE_APPEARANCE_STACK = 12,
	INVISIBLE = 13,
	EXAUST_CHARGE_APPEARANCE_STACK_INVISIBLE = 14
}
