namespace BlackRevival.Common.Enums;

public enum QuestType
{
    Login = 1,
    BeginAtField = 101,
    FinishGameCountRank = 201,
    FinishGameCountNormal,
    FinishGameSingleMode,
    FinishGameTeamMode,
    FinishGameMultiMode = 207,
    FinishGameMultiModeWithPerk,
    FinishGameCountUpperRank = 301,
    FinishGameUpperRankNormalMode,
    FinishGameUpperRankSingleMode,
    FinishGameUpperRankTeamMode,
    FinishGameUpperRankRankMode,
    WinGameCount = 501,
    MasteryRankReach = 601,
    KillCountCharacter = 801,
    KillCountMonster,
    UseCountSpecSkill = 1201,
    MakeItemCountUpperGrade = 1401,
    EquipFullItemCountUpperGrade = 1701,
    DamageValue = 701,
    PlayerDamage,
    KillCharacter = 801,
    KillMonster,
    KillTargetMonster = 804,
    KillCharacterBeforeRestrict,
    KillSlayer,
    KillCharacterTeamMode = 811,
    KillMonsterTeamMode,
    KillTargetMonsterTeamMode,
    AttackPlayer = 1101,
    UseSpecSkill = 1201,
    UseStance,
    UseSpecSkillTeamMode = 1211,
    AchieveVeteranGrade = 1301,
    MakeItemUpperGrade = 1401,
    MakeTargetItem,
    MakeItemUpperGradeBeforeRestrict,
    MakeTargetItem2,
    MakeItemUpperGradeBeforeRestrictTeamMode,
    TakeItem = 1501,
    TakeItemPlayerCorpse,
    MakeWeaponUpperGrade = 1601,
    EquipFullItemUpperGrade = 1701,
    AliveBeforeRestrict = 1801,
    UseBoosters = 2001,
    UseIceBox = 2101,
    UseOffensiveBox,
    UseDefensiveBox,
    UseBearsRoulette = 9007,
    UseSeasonRoulette,
    UseAglaiaRoulette,
    VoteFinishGameUpperRankNormalMode = 8302,
    VoteFinishGameUpperRankTeamMode = 8304,
    VoteFinishGameUpperRankRankMode,
    CurrencyUseAmountGold = 11001,
    CurrencyUseAmountGem,
    CurrencyUseAmountBp,
    UseVoteEvent = 11005,
    CurrencyUseAmountExperimentMemory,
    CurrencyUseGold = 11011,
    CurrencyUseGem,
    CurrencyUseBp,
    CurrencyUseVote = 11015,
    CurrencyUseExperimentMemory,
    CurrencyAccumulateGem,
    ClearAllWeeklyQuest = 12000,
    ClearAllDailyQuest = 12002,
    ClearAllAglaiaQuest,
    PurchaseDailyShop = 13001
}